###############################################################################
# This source file is part of the Tomviz project, https://tomviz.org/.
# It is released under the 3-Clause BSD License, see "LICENSE".
###############################################################################
"""XYZ writer for vtkMolecule port payloads.

The XYZ format is a plain-text representation of atomic positions with
one element-symbol + xyz line per atom; bonds are NOT preserved (XYZ has
no notion of them). If you need bonds, that's a future PDB/MOL writer.

  <num_atoms>
  <comment line>
  <symbol> <x> <y> <z>
  ..."""

from pathlib import Path


_PERIODIC_TABLE = None


def _periodic_table():
    """Lazy-load vtkPeriodicTable so importing this module never pulls
    in VTK unless something actually writes a molecule."""
    global _PERIODIC_TABLE
    if _PERIODIC_TABLE is None:
        import vtk
        _PERIODIC_TABLE = vtk.vtkPeriodicTable()
    return _PERIODIC_TABLE


def write_molecule_xyz(payload, target_path: Path) -> None:
    """Write a vtkMolecule to disk in standard XYZ format."""
    num_atoms_fn = getattr(payload, 'GetNumberOfAtoms', None)
    get_atom_fn = getattr(payload, 'GetAtom', None)
    if num_atoms_fn is None or get_atom_fn is None:
        raise TypeError(
            f'XYZ writer expected a vtkMolecule, got '
            f'{type(payload).__name__}')

    num_atoms = num_atoms_fn()
    pt = _periodic_table()

    with open(target_path, 'w') as f:
        f.write(f'{num_atoms}\n')
        f.write('Generated by tomviz-pipeline\n')
        for i in range(num_atoms):
            atom = get_atom_fn(i)
            atomic_number = atom.GetAtomicNumber()
            symbol = pt.GetSymbol(atomic_number) or 'X'
            pos = atom.GetPosition()
            f.write(
                f'{symbol} {pos[0]:.6f} {pos[1]:.6f} {pos[2]:.6f}\n')
